### ISSUE TITLE
Syntax error in slack

### ISSUE THREAD

**Issue by mnpenner** [OpenReplyDE/bbbackup#1]
I keep getting this error:

```
 % python bbbackup.py --help
Traceback (most recent call last):
  File "bbbackup.py", line 62, in <module>
    from slack.errors import SlackApiError
  File "/home/mark/bbbackup-master/bbak/lib/python3.5/site-packages/slack/__init__.py", line 4, in <module>
    from slack.web.client import WebClient  # noqa
  File "/home/mark/bbbackup-master/bbak/lib/python3.5/site-packages/slack/web/client.py", line 8, in <module>
    from slack.web.base_client import BaseClient, SlackResponse
  File "/home/mark/bbbackup-master/bbak/lib/python3.5/site-packages/slack/web/base_client.py", line 61
    ):
    ^
SyntaxError: invalid syntax
```

Any ideas what I have to do to fix this?

**Comment by or-staedtler** [comment]
Have you installed the required python modules?
I.e. did you execute ```pip install -r requirements.txt``` correctly?

**Comment by or-staedtler** [comment]
I will soon provide en enhanced version of bbbackup anyway, maybe I can add a detection for the required modules. Depends on how much time I can spend on this. ;-)

**Comment by mnpenner** [comment]
Yeah, I did install the requirements. Something funky with my environment I guess. Pretty sure you need Python 3.7, 3.5 isn't sufficient. Having multiple versions of pip and Python is too much of a headache; I gave up.

**Comment by or-staedtler** [comment]
I will look into it this weekend. In regard to python/pip issues... everything starts to became very easy and simple as soon as you consequently use a virtual environment (as described in the readme). I will update the current version of bbbackup soon and you could give it another try.

**Comment by or-staedtler** [comment]
You could try following:
1. `source bin/activate` in the directory of your installation to activate the virtual environment
2. `pip install --upgrade slackclient` to upgrade the Slack module

retry launching the software.

**Comment by or-staedtler** [comment]
Okay, I wasn't able to reproduce this error. 
Also if I type `pydoc slack.errors` it gives me as expected:

```
    class SlackApiError(SlackClientError)
     |  SlackApiError(message, response)
     |  
     |  Error raised when Slack does not send the expected response.
     |  
     |  Method resolution order:
     |      SlackApiError
     |      SlackClientError
     |      builtins.Exception
     |      builtins.BaseException
     |      builtins.object
```

So the relevant class is definitely there when you use `slackclient 2.0.0`. I may check soon if some newer version of slackclient may have issues. But right now the 2.0.0 works well in everyday backups here.

So closing this issue.
