### ISSUE TITLE
Cloning repos with spaces/special characters in the name fails

### ISSUE THREAD

**Issue by benleov** [OpenReplyDE/bbbackup#4]
Attempting to clone a bitbucket repository that contains spaces fails with the following error message:

```
REPO FAIL: /.../repo my-repo with spaces
Unable to clone repo my-repo with spaces. Exception: Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v git@bitbucket.org:team/my-repo with spaces.git /.../BACKUP_2019XXXX_UTC/my-repo with spaces
  stderr: 'Cloning into '/.../my-repo with spaces'...
Repository team/my-repo with spaces not found
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```
The git url should be:

```
git@bitbucket.org:team/my-repo-with-spaces.git
```

A possible solution might be to change 

```
REMOTE_REPO_PATH = 'git@bitbucket.org:{}/{}.git'.format( CONFIG_TEAM, repo_name)
```

in bbbackup.py to using the "full_name" field from the API, which is the same string used in Bitbucket URLs.

Cheers,

**Comment by or-staedtler** [comment]
I will soon hopefully find some time to fix this and also another issue relatedt to the fact, that only master branches are backed up right now.

**Comment by cal97g** [comment]
@or-staedtler I have submitted a pr for the latter issue, allowing all branches to be pulled with a conflig flag. See #5

**Comment by or-staedtler** [comment]
@cal97g thank you!! I'll have a quick look and check it.

**Comment by or-staedtler** [comment]
I just used your suggested way of using 'slug' instead of name. thx, again.
